name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm ci
        npm run build
    - name: Publish build to github-pages branch
      run: |
        sudo su
        mkdir BUILD
        cp -R docs BUILD/
        echo "Verify copy"
        cd BUILD
        ls
        echo "Verify done" 
        cd .. && ls
        echo "verify upper"
        cd .. && ls
        echo "verify upper^2"
      env:
        CI: true
