name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm ci
        npm run build
#   - name: Copy build files
#       run: |
#         sudo su
#         cd .. && mkdir BUILD and pwd
#         cd personal-portfolio
#         cp docs/* ../BUILD/ 
#         echo "Verify copy" && pwd
#         cd ../BUILD
#         git init
#         ls
#         echo "Verify done" && pwd
    - name: Push to github
      run: |
        sudo su
        cd docs
        git init
        git remote add upstream https://github.com/maybebored/personal-portfolio.git
        git checkout -b gh-pages
        git add .
        git status
        git push -u upstream gh-pages
      env:
        CI: true
